import * as fs from 'fs';
import * as path from 'path';
import type { GaussianBuffers } from './gaussian';

const SH_COEFF_DEG0 = Math.sqrt(1 / (4 * Math.PI));
const INV_SH_COEFF_DEG0 = 1 / SH_COEFF_DEG0;

export interface PlyBuildInput extends GaussianBuffers {
  imageWidth: number;
  imageHeight: number;
  focalPx: number;
}

function clamp01(value: number): number {
  if (value <= 0) return 0;
  if (value >= 1) return 1;
  return value;
}

function linearToSrgb(value: number): number {
  const x = clamp01(value);
  return x <= 0.0031308 ? 12.92 * x : 1.055 * x ** (1 / 2.4) - 0.055;
}

function rgbToSh0(rgb: number): number {
  return (rgb - 0.5) * INV_SH_COEFF_DEG0;
}

function safeLog(value: number, epsilon = 1e-8): number {
  return Math.log(Math.max(value, epsilon));
}

function safeLogit(value: number, epsilon = 1e-6): number {
  const x = Math.min(1 - epsilon, Math.max(epsilon, value));
  return Math.log(x / (1 - x));
}

function buildHeader(vertexCount: number): string {
  return [
    'ply',
    'format binary_little_endian 1.0',
    'comment generated by sharp-viewer',
    `element vertex ${vertexCount}`,
    'property float x',
    'property float y',
    'property float z',
    'property float f_dc_0',
    'property float f_dc_1',
    'property float f_dc_2',
    'property float opacity',
    'property float scale_0',
    'property float scale_1',
    'property float scale_2',
    'property float rot_0',
    'property float rot_1',
    'property float rot_2',
    'property float rot_3',
    'end_header',
    '',
  ].join('\n');
}

export function buildPlyBinary(input: PlyBuildInput): Buffer {
  const { count, meanVectors, singularValues, quaternions, colors, opacities } = input;
  if (meanVectors.length !== count * 3) throw new Error('meanVectors length mismatch');
  if (singularValues.length !== count * 3) throw new Error('singularValues length mismatch');
  if (quaternions.length !== count * 4) throw new Error('quaternions length mismatch');
  if (colors.length !== count * 3) throw new Error('colors length mismatch');
  if (opacities.length !== count) throw new Error('opacities length mismatch');

  const header = Buffer.from(buildHeader(count), 'utf8');
  const vertexBytes = count * 14 * 4;
  const output = Buffer.alloc(header.length + vertexBytes);
  header.copy(output, 0);
  let offset = header.length;

  const writeFloat = (value: number): void => {
    output.writeFloatLE(value, offset);
    offset += 4;
  };

  for (let i = 0; i < count; i++) {
    const v3 = i * 3;
    const v4 = i * 4;
    const x = meanVectors[v3];
    const y = meanVectors[v3 + 1];
    const z = meanVectors[v3 + 2];

    writeFloat(x);
    writeFloat(y);
    writeFloat(z);
    writeFloat(rgbToSh0(linearToSrgb(colors[v3])));
    writeFloat(rgbToSh0(linearToSrgb(colors[v3 + 1])));
    writeFloat(rgbToSh0(linearToSrgb(colors[v3 + 2])));
    writeFloat(safeLogit(opacities[i]));
    writeFloat(safeLog(singularValues[v3]));
    writeFloat(safeLog(singularValues[v3 + 1]));
    writeFloat(safeLog(singularValues[v3 + 2]));
    writeFloat(quaternions[v4]);
    writeFloat(quaternions[v4 + 1]);
    writeFloat(quaternions[v4 + 2]);
    writeFloat(quaternions[v4 + 3]);
  }

  if (offset !== output.length) throw new Error(`PLY size mismatch (${offset} != ${output.length})`);
  return output;
}

export async function writePlyFile(input: PlyBuildInput, outputDir: string, taskId: string): Promise<string> {
  await fs.promises.mkdir(outputDir, { recursive: true });
  const safeTaskId = taskId.replace(/[^a-zA-Z0-9_-]/g, '');
  const plyPath = path.join(outputDir, `sharp_${safeTaskId}_${Date.now()}.ply`);
  await fs.promises.writeFile(plyPath, buildPlyBinary(input));
  return plyPath;
}
